plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.3'
}

group = 'com.dracave.tags'
version = '2.0.0'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.6'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1'
    compileOnly 'com.zaxxer:HikariCP:5.1.0'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
}

processResources {
    filesMatching('plugin.yml') {
        expand(project.properties)
    }
}
