package com.dracave.tags.api;

public enum ShopStatus {
    SUCCESS,
    TITLE_NOT_FOUND,
    NOT_PURCHASABLE,
    PLAYER_OFFLINE,
    PERMISSION_DENIED,
    ALREADY_UNLOCKED,
    CURRENCY_UNAVAILABLE,
    INSUFFICIENT_FUNDS,
    PURCHASE_IN_PROGRESS,
    CANCELLED,
    PAYMENT_FAILED,
    REFUNDED,
    REFUND_PENDING,
    DATABASE_ERROR,
    SERVICE_UNAVAILABLE
}
